// ─── Information Reliability Agent — Types ────────────────────
// Google SRE-inspired trust scoring for all data sources.
// Methodology: NIST SP 800-160 trust composition + Google's
// "Monitoring Distributed Systems" 4 Golden Signals adapted
// for information reliability (freshness, agreement, provenance, consistency).

// ═══════════════════════════════════════════════════════════════
// Source Identity
// ═══════════════════════════════════════════════════════════════

/** Every data source the system consumes */
export type DataSourceId =
  | 'YAHOO_FINANCE'
  | 'TRADINGVIEW'
  | 'FINNHUB'
  | 'ALPHA_VANTAGE'
  | 'COINGECKO'
  | 'DEXSCREENER'
  | 'FRED'
  | 'POLYMARKET'
  | 'TAAPI'
  | 'SEC_EDGAR'
  | 'STOCKTWITS'
  | 'CNBC'
  | 'MARKETWATCH'
  | 'RSS_FEED'
  | 'GOOGLE_ALERTS'
  | 'LOCAL_INDICATORS';  // computed by our own engine

/** Source metadata — static calibration */
export interface SourceProfile {
  id: DataSourceId;
  tier: 1 | 2 | 3;               // 1=primary (exchange-level), 2=secondary (aggregator), 3=supplementary (sentiment/news)
  dataType: 'PRICE' | 'INDICATOR' | 'SENTIMENT' | 'FUNDAMENTAL' | 'EVENT';
  baseReliability: number;         // 0-100, prior from backtested accuracy
  latencyMs: number;               // expected data staleness window
  refreshIntervalMs: number;       // how often this source updates
  hasCrossValidation: boolean;     // can be verified against another source
}

// ═══════════════════════════════════════════════════════════════
// Source Observation — single data point from a source
// ═══════════════════════════════════════════════════════════════

export interface SourceObservation {
  sourceId: DataSourceId;
  symbol: string;
  timestamp: number;              // when the data was fetched
  dataTimestamp?: number;         // when the data was generated by the source (if known)
  price?: number;
  direction?: 'BULLISH' | 'BEARISH' | 'NEUTRAL';
  confidence?: number;            // source-native confidence (0-100)
  indicators?: Record<string, number>;  // e.g. { RSI: 32, MACD: -0.5 }
  sentiment?: 'BULLISH' | 'BEARISH' | 'NEUTRAL';
  sentimentScore?: number;        // -100 to +100
  raw?: string;                   // original text/headline for provenance
}

// ═══════════════════════════════════════════════════════════════
// Reliability Scores — per-source and composite
// ═══════════════════════════════════════════════════════════════

export interface SourceReliabilityScore {
  sourceId: DataSourceId;
  freshnessScore: number;         // 0-100 — how recent is the data
  accuracyScore: number;          // 0-100 — historical accuracy (from D1 tracking)
  agreementScore: number;         // 0-100 — does this source agree with others
  provenanceScore: number;        // 0-100 — is the source itself trustworthy today (not down, not stale)
  compositeScore: number;         // weighted aggregate
  penalty: string | null;         // if active penalty, explain why
}

export interface ContradictionReport {
  type: 'PRICE_DIVERGENCE' | 'DIRECTION_CONFLICT' | 'INDICATOR_MISMATCH' | 'SENTIMENT_SPLIT' | 'STALE_VS_FRESH';
  severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  sourceA: DataSourceId;
  sourceB: DataSourceId;
  detail: string;
  resolution: 'TRUST_A' | 'TRUST_B' | 'AVERAGE' | 'DISCARD_BOTH' | 'UNRESOLVED';
  resolutionReason: string;
}

export interface RecencyAssessment {
  oldestSourceAge: number;        // ms
  freshestSourceAge: number;      // ms
  medianAge: number;              // ms
  allFresh: boolean;              // all within acceptable window
  staleCount: number;             // how many are too old
  staleSources: DataSourceId[];   // which ones
}

export interface ReliabilityVerdict {
  symbol: string;
  timestamp: number;

  // Composite trust score — the one number Z.AI cares about most
  trustScore: number;             // 0-100

  // Trust tier — for quick gating
  trustTier: 'VERY_HIGH' | 'HIGH' | 'MEDIUM' | 'LOW' | 'UNTRUSTED';

  // Per-source breakdown
  sourceScores: SourceReliabilityScore[];

  // Contradictions found
  contradictions: ContradictionReport[];

  // Recency assessment
  recency: RecencyAssessment;

  // Cross-source agreement (number of sources that agree on direction)
  directionConsensus: {
    bullish: number;
    bearish: number;
    neutral: number;
    total: number;
    consensusDirection: 'BULLISH' | 'BEARISH' | 'MIXED' | 'NEUTRAL';
    consensusStrength: number;    // 0-100
  };

  // Actionable summary for Z.AI prompt injection
  summary: string;

  // Recommended confidence adjustment (multiply into trade confidence)
  confidenceMultiplier: number;   // 0.0 - 1.2 (can boost up to +20% for very high trust)
}

// ═══════════════════════════════════════════════════════════════
// Source Performance Tracking — D1 persisted
// ═══════════════════════════════════════════════════════════════

export interface SourcePerformanceRecord {
  source_id: string;
  date: string;                   // YYYY-MM-DD
  total_signals: number;
  correct_signals: number;        // matched trade outcome
  accuracy_rate: number;          // 0-1
  avg_freshness_ms: number;
  avg_agreement_score: number;
  bullish_bias_pct: number;       // 0-1 — systematic directional bias
  downtime_minutes: number;       // source unavailability
  updated_at: number;
}

// ═══════════════════════════════════════════════════════════════
// Agent Health & Stats
// ═══════════════════════════════════════════════════════════════

export interface ReliabilityAgentStats {
  totalAssessments: number;
  avgTrustScore: number;
  contradictionsDetected: number;
  staleDataBlocked: number;
  highTrustApprovals: number;
  lowTrustRejections: number;
  sourceAccuracyMap: Record<string, number>;  // sourceId → rolling accuracy
  lastResetAt: number;
}
